trapez_integration: trapez_integration.c
	gcc -o trapez_integration -lm trapez_integration.c

trapez_integration_mpi: trapez_integration_mpi.c
	mpicc -o trapez_integration -lm trapez_integration.c

clean:
	rm trapez_integration trapez_integration_mpi
