std_dev: std_dev.c
	mpicc -o std_dev -lm std_dev.c

std_dev_task1: std_dev_task1.c
	mpicc -o std_dev_task1 -lm std_dev_task1.c

std_dev_task2: std_dev_task2.c
	gcc -o std_dev_task2 -lm std_dev_task2.c

std_dev_task3: std_dev_task3.c
	mpicc -o std_dev_task3 -lm std_dev_task3.c

clean:
	rm std_dev std_dev_task1 std_dev_task2 std_dev_task3
