function [nproc,npts,time_v1,error_v1,time_v2,error_v2,time_v3,error_v3] = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [NPROCNPTSTIME_V1ERROR_V1TIME_V2ERROR_V2TIME_V3ERROR_V3, VARNAME2,
%  VARNAME3, VARNAME4, VARNAME5, VARNAME6, VARNAME7, VARNAME8] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [NPROCNPTSTIME_V1ERROR_V1TIME_V2ERROR_V2TIME_V3ERROR_V3, VARNAME2,
%  VARNAME3, VARNAME4, VARNAME5, VARNAME6, VARNAME7, VARNAME8] =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [nprocnptstime_v1error_v1time_v2error_v2time_v3error_v3, VarName2, VarName3, VarName4, VarName5, VarName6, VarName7, VarName8] = importfile1("/Volumes/GoogleDrive/My Drive/teaching/ME471:571/ME471_571 Spring 2021/Labs/Week 8/dudx.o312354", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Mar-2021 14:48:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["nprocnptstime_v1error_v1time_v2error_v2time_v3error_v3", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName4", "VarName6"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName2", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName2", "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
nproc = tbl.nprocnptstime_v1error_v1time_v2error_v2time_v3error_v3;
npts = tbl.VarName2;
time_v1 = tbl.VarName3;
error_v1 = tbl.VarName4;
time_v2 = tbl.VarName5;
error_v2 = tbl.VarName6;
time_v3 = tbl.VarName7;
error_v3 = tbl.VarName8;
end